### ISSUE TITLE
verk1 - day1, success og error log

### ISSUE THREAD

**Issue by M3ttle** [hgop/syllabus-2017#11]
Lýsingin er svolítið óljós, en hvort á að prenta í success skrá lið A ef liður B klikkar?
Þá myndi koma success skrá með lið A og error skrá með lið B.

Eða ef liður B klikkar þá koma villuboð um það og fjarlægir success skrána?

Einnig, eigum við að skrifa outputtið frá terminal hvað hann er að gera í success/error skránum (semsagt skref fyrir skref), eða bara "A feilaði" eða "B feilaði" ?

**Comment by IronPeak** [comment]
Það verður bara til success log ef allt gengur upp, annars verður til error log.
Þið ráðið hvernig þið gerið failure log-inn, það þarf bara að vera augljóst hvað failaði.
Example:
Some error output from the install command
Program X failed to install.
