### ISSUE TITLE
Á container ID að vera á localhost? 

### ISSUE THREAD

**Issue by annakrih** [hgop/syllabus-2017#13]
Ég er í þessu skrefi: https://github.com/hgop/syllabus-2017/blob/master/Assignment/Day2/day2.md#run-the-app 

Maður að nota commandið `docker run -p 3000:3000 pagecounter` og fá útúr því síðuna "Failed to connect to redis :'(" á localhost, allt í lagi með það. 

Svo er strax farið í að keyra kommandið `docker run -d -p 3000:3000 pagecounter` og þá stendur að maður eigi að sjá CONTAINER ID á localhost... ég skil ekki, ég fæ bara ennþá sömu síðu "Failed to connect to redis :'(", ekkert container ID þar...

Það er semsagt þessi lína sem ég er að pæla í: "You’ll see that CONTAINER ID matches what’s on http://localhost:3000."

Er ég að misskilja leiðbeiningarnar eða gera eitthvað vitlaust?

**Comment by unnsteinngardars** [comment]
Þegar þú keyrir docker run -p -d 3000:3000 pagecounter þá processinn keyrður upp í bakgrunni og þú getur haldið áfram að vinna í skelinni og þarft þar að leiðandi ekki að opna nýjan tab í henni.

Þegar þú svo keyrir docker container ls þá færðu upp container ID fyrir þær keyrslur sem eru keyrandi og getur notað það id með docker container stop ID til að drepa keyrsluna. Sama og gerist þegar þú gerir ctrl+D þegar þú keyrðir docker run -p 3000:3000 pagecounter
