### ISSUE TITLE
Amazon verkefni - Connection reset by peer

### ISSUE THREAD

**Issue by clover89** [hgop/syllabus-2017#14]
Hæhæ

Ég er búinn að fylgja öllum skrefum gaumgæfilega en þegar ég reyni að keyra docker forritið frá day2 (week1:part2) inni á Amazon-vélinni og geri curl localhost þá fæ ég bara curl: (56) Revc failure: Connection reset by peer.

Það virkar vel að að runna þennan sama container locally hjá mér en ekki á Amazon. Ég er búinn að prófa example hello world Docker containerinn úr tutorialinu og hann virkar fínt á Amazon-vélinni. 

Dettur einhverjum í hug hvað veldur þessu?
Ég er búinn að vera að hárreita mig í meira en 2 klst. núna yfir þessu.

**Comment by saethor** [comment]
Ertu ekki örruglega búinn að opna á port 80 í þeirri Security Group sem þín vél er að nota, annað hvort fyrir alla eða allavega á þeirri ip tölu sem þú ert á. Einnig þarftu að breyta port forwardinu í docker-compose þannig að það sé að forwarda porti 3000 yfir á port 80 (80:3000 í staðin fyrir 3000:3000)

**Comment by clover89** [comment]
Ég er búinn að breyta port í 80:3000 og í 80:5000 í docker-compose. Þarf að gera eitthvað meira? Hvorugt hafði áhrif.

**Comment by saethor** [comment]
Þarft að restart containernum, það virkar ekki að breyta í "80:5000" nema að þú breytir javascript appinu líka, það er hlusta á port 3000. Hvaðan ertu gera curl localhost? Inn í amazon vélinni eða frá þinni eigin vél?

**Comment by Fanneyyy** [comment]
Já í AWS tutorialinu þá eruð þið bara að starta ykkar image frá docker hub e.g. 

`clover89/week1:part2`

og þá getiði startað því með   

`docker run -d -p 80:3000 clover89/week1:part2`   

eins og @clover89 gerði, þá er alveg rétt að það komi   

`Failed to connect to redis :'(`   

því redis er ekki í gangi.
Þarna eruð þið ekki að nota`docker-compose.yml` file-inn


það var ekki partur af tutorialinu, en ef þið viljið keyra bæði client (app image) og gagnagrunn (redis) þá þurfið þið að
* installa `docker-compose` á aws vélina
* copy-a `docker-compose.yml` inná vélina
* keyra `docker-compose up`
