### ISSUE TITLE
database undefined

### ISSUE THREAD

**Issue by unnsteinngardars** [hgop/syllabus-2017#16]
const database = require('./database');
þessi lína skilar mér að database sé undefined.
export kóðinn fór neðst í database.js fælinn
Einhverjar hugmyndir um hvað gæti verið að stríða mér?

**Comment by Fanneyyy** [comment]
Ertu að fá þessa villu þegar þú keyrir docker-compose up?
Gæti verið að það vanti `database.js` í `Dockerfile`?
