### ISSUE TITLE
AWS student account - Create user Admin?

### ISSUE THREAD

**Issue by disaerna** [hgop/syllabus-2017#17]
Þegar ég er inná accountinum sem þið settuð upp, þarf ég líka að fylgja öllum skrefunum, búa til IAM user administrator, grúppu og allt það ?

**Comment by disaerna** [comment]
Okey, ég addaði access key á mig, en get samt ekki búið til ec2 instance því ég fæ non authorized á að búa til nýtt key-pair fyrir security groupu. What to do?!

**Comment by bensi94** [comment]
Okei sko eins og ég og fleiri gerðum þetta, þá fórum við eftir þessum tutorial þar sem hann býr til IAM admin og grúbbu, ég veit ekkert um hvort það sé eina leiðin en líklega ekki. Ég skil það samt þannig að þetta sé öryggisráðstofun þannig þær skipanir sem þú ert að keyra með AWS í console séu ekki keyrðar af root usernum þínum, heldur þessum admin user sem þú bjóst til.

Hins vegar ef þú ert að gera manual skrefin á part 1 þá var ég að gera það á root í browser, ss búa til security group, key-pair og upphaflega instanceinn (en auðvitað hægt að gera það líka í console).

En til að geta nota aws skipanir í console og , þá ferðu (enn logguð inná root í browser) finnur IAM og ýtir þar á admin userinn sem þú bjóst til, og gerir "generate acess key" þar færðu upp acess key og secret acess key, þá opnarðu console og gerir "AWS configure" þá færðu upp reitina þar sem þú setur inn þessa acess keys sem þú varst að generatea og region (eu-west-1 notaður í gefna scriptinu) svo skildi ég default text ouput eftir tómt. Eftir þetta ættirðu að vera logguð inná aws admin aðganginn þinn í console og ættir að geta gefið skipanir (og runnað scriptum sem nota þær) í consolenum.

Vona að þessar upplýsingar hjálpi.

**Comment by disaerna** [comment]
Takk fyrir þetta :) Komið instance running !
Nú er ég bara í veseni með að ég hef ekki aðgang til þess að búa til container, kemur un authorized aftur :(

**Comment by disaerna** [comment]
![image](https://user-images.githubusercontent.com/19873770/33460786-b9a92ae0-d627-11e7-8aa8-0928fa092033.png)

Er inná **eu-west-1**.console.aws...

**Comment by IronPeak** [comment]
þú ert að reyna að búa til ECR (Elastic Container Registry) en í verkefninu á að búa til EC2 instance :)

**Comment by disaerna** [comment]
Já það er komið hehe. En ég fylgdi bara leiðbeiningunum sem var bent á úr degi 2! haha :) Takk fyrir þetta
