### ISSUE TITLE
Running Instance of the application.

### ISSUE THREAD

**Issue by SenpaiPlz** [hgop/syllabus-2017#19]
With regards to this comment, are you expecting the public dns adress of the instance? And furthermore, I would presume that this instance would need to be accessible by you, and therefore have a security group policy that allows http connections over all ips, Unlike the setup in the guide where it was blocked off to all, except the computers public ip that set up the security group?

**Comment by IronPeak** [comment]
Yes your application does have to be accessible over port 80 from any source.
Which setup guide are you referring to?

**Comment by SenpaiPlz** [comment]
Well its not really a setup guide, but I was referring to the code snippets that were provided on Day3, in particular the Create an EC2 instance snippet had code that would setup the security group and their policies only allowing access to a single public IP.

This however is not a difficult change to make, Thank you for clearing it up.
