### ISSUE TITLE
No access between EC2 instances

### ISSUE THREAD

**Issue by Snojo** [hgop/syllabus-2017#23]
What am I missing? 
I have everything up and running more or less, except that I can't scp anything between ec2 instances or ssh between them. 
I'm using the correct key so I don't quite know what to do now. 
A special configuration I'm missing?

```
ssh: connect to host ec2-18-216-129-185.us-east-2.compute.amazonaws.com port 22: Connection refused
lost connection
ssh: connect to host ec2-18-216-129-185.us-east-2.compute.amazonaws.com port 22: Connection refused
lost connection
ssh: connect to host ec2-18-216-129-185.us-east-2.compute.amazonaws.com port 22: Connection refused
lost connection
ssh: connect to host ec2-18-216-129-185.us-east-2.compute.amazonaws.com port 22: Connection refused
lost connection
SCP finished. Lets run the shit
ssh: connect to host ec2-18-216-129-185.us-east-2.compute.amazonaws.com port 22: Connection refused
ssh: connect to host ec2-18-216-129-185.us-east-2.compute.amazonaws.com port 22: Connection refused
ssh: connect to host ec2-18-216-129-185.us-east-2.compute.amazonaws.com port 22: Connection refused
```

**Comment by SenpaiPlz** [comment]
I did notice that the overly aggressive firewall (Authorization) settings in the base script were causing me some problem. I would suggest checking that and making sure that the .pem is being used.

**Comment by saethor** [comment]
Are you trying to connect from one ec2 instance to another?
We had that problem and fixed it by changing the firewall rule with port 22 from using the public ip address of the jenkins instance to the private ip address.

You can get your private ip with this snippet

`MY_PRIVATE_IP=$(hostname -I | cut -d' ' -f1)`
