### ISSUE TITLE
Npm Jenkins vesen

### ISSUE THREAD

**Issue by atlit06** [hgop/syllabus-2017#25]
Er ég bara að fá svona lélega aws vél eða er þetta eitthvað almennt vandamál, ég bara get ekki haft npm install í Jenkinsfile skránni, annaðhvort er Jenkins 2 tíma að keyra OG failar á að installa npm eða crashar og ég þarf að reboot-a aws vélinni. 
Yarn hinsvegar snarvirkar, en það stendur í Readme að til að keyra client testin þarf npm þ.a. hvað er hægt að gera í þessu vandamáli?

**Comment by saethor** [comment]
Þú ættir að geta installað með yarn án vandræða en notað svo npm til þess að keyra commandin
