### ISSUE TITLE
AWS web services integration með stúdentaaðgangi

### ISSUE THREAD

**Issue by alli93** [hgop/syllabus-2017#27]
Fylgjandi leiðbeiningum Datadog t.þ.a. innleiða það með AWS þarf að gefa upp AWS account id og role name. Stúdentaaðganginum er hinsvegar ekki leyfilegt að framkvæma þessa aðgerð með sínu role og id. 
Er þetta nauðsynleg aðgerð fyrir nemendur með stúdentaaðgang? Er kannski nú þegar búið að gera þetta fyrir aðgangana okkar?

**Comment by kthorri** [comment]
Þú innleiðir það ekki með AWS, installar eingöngu inná ec2 instance'ið þitt.. (þetta optional aws skref þarf ekki)
