### ISSUE TITLE
Vandamál með react-scripts build 

### ISSUE THREAD

**Issue by alli93** [hgop/syllabus-2017#28]
Ég var með virkandi deployment en út úr bláinu byrjaði react-scripts build (kallað frá npm buildclient  frá npm build í Jenkins instance) að láta deploymentið mitt staðna. 

Stundum virkar það eftir nokkrar mínutur og skilar:

export NODE_PATH=./src/ && react-scripts build

Creating an optimized production build...
Cannot contact : java.nio.channels.ClosedByInterruptException

Eftir það heldur deployment áfram án vandamála. Á öðrum tímum hef ég fengið segmentation fault, eða fork: cannot allocate memory og deployment failar. Öll önnur ferli í pípunni eru mjög smooth en um leið og react-scripts build er kallað byrjan vélin að kafna.

Ég hef prufað að endurræsa ec2 instance, enduræsa jenkins service, enduruppsetja nodejs (version 9.3 er þ.s. week3 forkið installar og það er það sem ég er að nota). Enduruppsetja Java, og gera npm cache clean ásamt því að eyða öllu úr workspace. Minnisnotkun fer frá 70% upp í 90% þegar ég triggera deployment, og laust gagnamagn á velínni er 50%. Hefur einhver einhverjar hugmyndir um frá hverju þetta gæti stafað?

**Comment by saethor** [comment]
Við lentum í svipuðu þegar að við settup upp datadog agent á vélinni. Um leið og við slökktum á honum þá fór þetta að verða smooth aftur.

**Comment by alli93** [comment]
Þetta var orsökin að þessu, þakka þér! 

Ætla að prufa að reinstalla datadog og sjá hvort það leyfir mér að nota þjónustuna á meðan ég deploya.
