### ISSUE TITLE
Linux fyrir mac notendur

### ISSUE THREAD

**Issue by unnsteinngardars** [hgop/syllabus-2017#3]
Er must að setja upp linux fyrir þá sem eru með mac os? Sendi þér mail en svaraðir ekki þar svo ég ákvað að prufa hér

**Comment by hap2000** [comment]
Miklu betra að fá fyrirspurnirnar hingað, þá sjá allir. 
Já við viljum helst hafa alla á sambærilegu umhverfi. Það er vissulega hægt að leysa allt sem við erum að gera á Mac os en það er munur á scriptunum sem við erum að vinna með á milli þessara stýrikerfa. Verkefnið verður þannig að við munum gefa lausn við verkefninu eftir hverja viku þannig að allir byrji á sama stað í byrjun hverrar viku. Við getum ekki tryggt að það virki á Mac os.

**Comment by unnsteinngardars** [comment]
Ok ég vill meina að ég hafi sett upp ubuntu linux á usb lykil án vandræða. En hinsvegar þegar ég ætla að reyna að boota hann þá fæ ég hann ekki upp í bootloadernum. Ætlaði að installa clover bootloader en það er eitthvað issue þar sem ég er nýlega búinn að uppfæra mac os yfir í High sierra.

Hefuru einhverja reynslu af þessu sjálfur með mac og að gera bootable linux usb?

**Comment by stefaneg** [comment]
Ef þú ert með 8GB eða meira í minni, þá mæli ég með að nota virtualvél með Ubuntu 16.04, sem þú getur til dæmis náð í hér: http://www.osboxes.org/ubuntu-16-04-3-images-available-virtualbox-vmware/ 

Varðandi USB boot, virkar þessi hér aðferð ekki hjá þér ?  http://www.idownloadblog.com/2015/09/14/how-to-start-up-mac-from-bootable-media/

**Comment by unnsteinngardars** [comment]
Nei ég fæ ekki upp neitt option fyrir usb. Ég fór samt successfully í
gegnum ferlið við að installa ubuntu og installaði á usb lykilinn. En ég
verð að reyna að hjakka í þessu eitthvað víst mac os dugar ekki.

**Comment by unnsteinngardars** [comment]
Er ég ekki að skilja það rétt að ég geri bootable USB og nota hann síðan til að installa á annan usb? Eða á ég að geta bara keyrt linux beint af USB kubbnum sem ég gerði með unetbootin?

**Comment by stefaneg** [comment]
Þú átt að geta keyrt beint af USB kubbnum, ef þú settir upp þannig image. Þú vilt sem sagt ekki setja upp installer image heldur keyrsluimage.

**Comment by stefaneg** [comment]
Annars þá mæli ég með að nota virtual vél frekar en USB boot ef þú ert með nógu stóra vél.

**Comment by unnsteinngardars** [comment]
Vélin mín er ekki nógu öflug í það, reyndi með windows einusinni og það var lost case.

En annars á ég að gera try ubuntu bara i hvert sinn sem ég boota eða?

**Comment by stefaneg** [comment]
Við höfum endurskoðað Linux kröfuna, og ákveðið að styðja einnig að verkefnið sé unnið á osX.

**Comment by unnsteinngardars** [comment]
Gæti þá ekki orðið neitt issue ef tveir vinna saman, einn á mac OS og einn á windows?

**Comment by stefaneg** [comment]
Munum ekki styðja Windows, menn nota það alfarið á eigin ábyrgð.
